# Generated by Django 6.0.2 on 2026-02-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantActivity',
            fields=[
                ('event_id', models.UUIDField(help_text='Unique identifier for the event', primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(db_index=True, help_text='Merchant identifier in format MRC-XXXXXX', max_length=50)),
                ('event_timestamp', models.DateTimeField(db_index=True, help_text='ISO 8601 timestamp when the event occurred')),
                ('product', models.CharField(choices=[('POS', 'POS'), ('AIRTIME', 'Airtime'), ('BILLS', 'Bills'), ('CARD_PAYMENT', 'Card Payment'), ('SAVINGS', 'Savings'), ('MONIEBOOK', 'Moniebook'), ('KYC', 'KYC')], db_index=True, help_text='Product category', max_length=50)),
                ('event_type', models.CharField(choices=[('CARD_TRANSACTION', 'Card Transaction'), ('CASH_WITHDRAWAL', 'Cash Withdrawal'), ('TRANSFER', 'Transfer'), ('AIRTIME_PURCHASE', 'Airtime Purchase'), ('DATA_PURCHASE', 'Data Purchase'), ('ELECTRICITY', 'Electricity'), ('CABLE_TV', 'Cable TV'), ('INTERNET', 'Internet'), ('WATER', 'Water'), ('BETTING', 'Betting'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('INVOICE_PAYMENT', 'Invoice Payment'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('INTEREST_CREDIT', 'Interest Credit'), ('AUTO_SAVE', 'Auto Save'), ('SALE_RECORDED', 'Sale Recorded'), ('INVENTORY_UPDATE', 'Inventory Update'), ('EXPENSE_LOGGED', 'Expense Logged'), ('DOCUMENT_SUBMITTED', 'Document Submitted'), ('VERIFICATION_COMPLETED', 'Verification Completed'), ('TIER_UPGRADE', 'Tier Upgrade')], help_text='Type of activity within the product', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in NGN (0 for non-monetary events)', max_digits=15)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], db_index=True, help_text='Event status: SUCCESS, FAILED, or PENDING', max_length=20)),
                ('channel', models.CharField(help_text='Channel: POS, APP, USSD, WEB, or OFFLINE', max_length=20)),
                ('region', models.CharField(help_text="Merchant's operating region", max_length=50)),
                ('merchant_tier', models.CharField(help_text='KYC tier: STARTER, VERIFIED, or PREMIUM', max_length=20)),
            ],
            options={
                'db_table': 'merchant_activity',
                'ordering': ['-event_timestamp'],
                'indexes': [models.Index(fields=['status'], name='merchant_ac_status_f79ed0_idx'), models.Index(fields=['product'], name='merchant_ac_product_446bb6_idx'), models.Index(fields=['event_timestamp'], name='merchant_ac_event_t_874f7c_idx'), models.Index(fields=['merchant_id'], name='merchant_ac_merchan_8537c0_idx'), models.Index(fields=['merchant_id', 'status'], name='merchant_ac_merchan_56a228_idx'), models.Index(fields=['product', 'status'], name='merchant_ac_product_8df57e_idx')],
            },
        ),
    ]
