# Generated by Django 6.0.2 on 2026-02-21 12:01

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantActivity',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the event', primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(db_index=True, help_text='Merchant identifier in format MRC-XXXXXX', max_length=50)),
                ('event_timestamp', models.DateTimeField(blank=True, db_index=True, help_text='When the event occurred (ISO 8601 format)', null=True)),
                ('product', models.CharField(db_index=True, help_text='Product category: POS, AIRTIME, BILLS, CARD_PAYMENT, SAVINGS, MONIEBOOK, KYC', max_length=50)),
                ('event_type', models.CharField(db_index=True, help_text='Type of activity specific to the product', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transaction amount in NGN (0 for non-monetary events)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(db_index=True, help_text='Event status: SUCCESS, FAILED, PENDING', max_length=20)),
                ('channel', models.CharField(help_text='Channel: POS, APP, USSD, WEB, OFFLINE', max_length=20)),
                ('region', models.CharField(help_text="Merchant's operating region", max_length=100)),
                ('merchant_tier', models.CharField(help_text='KYC tier: STARTER, VERIFIED, PREMIUM', max_length=20)),
            ],
            options={
                'db_table': 'merchant_activities',
                'ordering': ['-event_timestamp'],
                'indexes': [models.Index(fields=['merchant_id', 'status'], name='merchant_ac_merchan_90cd32_idx'), models.Index(fields=['product', 'status'], name='merchant_ac_product_163f19_idx'), models.Index(fields=['event_timestamp', 'status'], name='merchant_ac_event_t_264ee5_idx'), models.Index(fields=['product', 'event_type'], name='merchant_ac_product_4f9080_idx')],
            },
        ),
    ]
