# Generated by Django 6.0.2 on 2026-02-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='merchantactivity',
            index=models.Index(fields=['status', 'event_timestamp', 'merchant_id'], name='merchant_ac_status_fcf63a_idx'),
        ),
    ]
